# Generated by Django 5.0.1 on 2024-01-20 08:28

import hello_azure.models
import hello_azure.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(storage=hello_azure.storage.OverwriteStorage(), upload_to=hello_azure.models.video_directory_path)),
            ],
        ),
    ]
